name: agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - weaviate-client>=4.4.0
    - fastembed>=0.2.0
    - numpy>=1.24.0
    - python-dotenv>=1.0.0
    - pandas>=2.0.0
    - jupyter>=1.0.0
    - tqdm>=4.65.0